version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    command: mongod
    ports:
      - "27017:27017"
  backend:
    container_name: backend
    restart: always
    build: ./
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    links:
      - mongo
  client:
    container_name: client
    restart: always
    build: ./client/
    volumes:
      -  ./client:/app/
    depends_on:
      - backend
    ports:
      - "3000:3000"
